[package]
name = "tauri-plugin-streamlocker-player"
authors = ["YeonV"]
version = "0.0.1"
edition = "2021"

[dependencies]
tauri = { version = "2.8.5", features = [] }
serde = { version = "1.0", features = ["derive"] }
jni = "0.21.1"
